In [22]:
from google.colab import drive
drive.mount ('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [23]:
import pandas as pd

#Membaca file dataset CSV dari Google Drive lalu menyimpannya ke variabel data
data = pd.read_csv('/content/drive/MyDrive/Tugas Statistika Random Sampling & T Distribusi/MovieData-2018-2020.csv')

#Menampilkan 5 baris pertama dari dataset
data.head()

,name,rating,genre,year,released,score,votes,director,writer,star,country,budget,gross,company,runtime
0,A Quiet Place,PG-13,Drama,2018,"April 6, 2018 (United States)",7.5,456000.0,John Krasinski,Bryan Woods,Emily Blunt,United States,17000000.0,3.503204e+08,Paramount Pictures,90.0
1,Avengers: Infinity War,PG-13,Action,2018,"April 27, 2018 (United States)",8.4,897000.0,Anthony Russo,Christopher Markus,Robert Downey Jr.,United States,321000000.0,2.048360e+09,Marvel Studios,149.0
2,Deadpool 2,R,Action,2018,"May 18, 2018 (United States)",7.7,505000.0,David Leitch,Rhett Reese,Ryan Reynolds,Canada,110000000.0,7.864705e+08,Twentieth Century Fox,119.0
3,Bohemian Rhapsody,PG-13,Biography,2018,"November 2, 2018 (United States)",7.9,476000.0,Bryan Singer,Anthony McCarten,Rami Malek,United Kingdom,52000000.0,9.119026e+08,Twentieth Century Fox,134.0
4,Black Panther,PG-13,Action,2018,"February 16, 2018 (United States)",7.3,661000.0,Ryan Coogler,Ryan Coogler,Chadwick Boseman,United States,200000000.0,1.347598e+09,Marvel Studios,134.0

In [24]:
data["genre"].value_counts()

genre
Action       88
Comedy       45
Drama        38
Biography    29
Animation    23
Adventure    19
Horror       15
Crime        12
Fantasy       3
Thriller      1
Sci-Fi        1
Name: count, dtype: int64

In [25]:
#menghilangkan genre yang hanya berisi 1 judul
filtered_data = data.groupby('genre').filter(lambda x: len(x) > 1)
filtered_data["genre"].value_counts()

genre
Action       88
Comedy       45
Drama        38
Biography    29
Animation    23
Adventure    19
Horror       15
Crime        12
Fantasy       3
Name: count, dtype: int64

In [32]:
#stratifed sample genre
_, stratified_sample = train_test_split(
    filtered_data,
    test_size=0.2,               # Ambil 20% data dari setiap kelas
    stratify=filtered_data['genre'],      # Stratifikasi berdasarkan kolom 'genre'
    random_state=40
)
# Hasil stratified_sample berisi 20% sampel dari setiap genre
stratified_sample

,name,rating,genre,year,released,score,votes,director,writer,star,country,budget,gross,company,runtime
22,Annihilation,R,Adventure,2018,"February 23, 2018 (United States)",6.8,292000.0,Alex Garland,Alex Garland,Natalie Portman,United Kingdom,40000000.0,4.307092e+07,Paramount Pictures,115.0
78,Searching,PG-13,Drama,2018,"August 31, 2018 (United States)",7.6,148000.0,Aneesh Chaganty,Aneesh Chaganty,John Cho,United States,880000.0,7.546204e+07,Screen Gems,102.0
155,Captain Marvel,PG-13,Action,2019,"March 8, 2019 (United States)",6.8,478000.0,Anna Boden,Anna Boden,Brie Larson,United States,160000000.0,1.128463e+09,Walt Disney Pictures,123.0
226,The Kitchen,R,Action,2019,"August 9, 2019 (United States)",5.5,18000.0,Andrea Berloff,Andrea Berloff,Melissa McCarthy,United States,38000000.0,1.598003e+07,BRON Studios,102.0
124,Hell Fest,R,Horror,2018,"September 28, 2018 (United States)",5.5,15000.0,Gregory Plotkin,Seth M. Sherwood,Cynthea Mercado,United States,5500000.0,1.816093e+07,CBS Films,89.0
26,Death Wish,R,Action,2018,"March 2, 2018 (United States)",6.3,67000.0,Eli Roth,Joe Carnahan,Bruce Willis,United States,30000000.0,4.956271e+07,Cave 76,107.0
87,Hotel Artemis,R,Action,2018,"June 8, 2018 (United States)",6.1,49000.0,Drew Pearce,Drew Pearce,Jodie Foster,United Kingdom,15000000.0,1.331358e+07,The Ink Factory,94.0
183,Toy Story 4,G,Animation,2019,"June 21, 2019 (United States)",7.7,217000.0,Josh Cooley,John Lasseter,Tom Hanks,United States,200000000.0,1.073395e+09,Pixar Animation Studios,100.0
89,Book Club,PG-13,Comedy,2018,"May 18, 2018 (United States)",6.1,26000.0,Bill Holderman,Bill Holderman,Diane Keaton,United States,10000000.0,1.044382e+08,Apartment Story,104.0
247,Breakthrough,PG,Biography,2019,"April 17, 2019 (United States)",6.3,8800.0,Roxann Dawson,Joyce Smith,Marcel Ruiz,United States,14000000.0,5.044436e+07,Fox 2000 Pictures,116.0
100,Andhadhun,Not Rated,Crime,2018,"October 5, 2018 (United States)",8.2,79000.0,Sriram Raghavan,Arijit Biswas,Ayushmann Khurrana,India,4500000.0,6.247534e+07,Matchbox Pictures,139.0
203,A Beautiful Day in the Neighborhood,PG,Biography,2019,"November 22, 2019 (United States)",7.3,67000.0,Marielle Heller,Micah Fitzerman-Blue,Tom Hanks,China,25000000.0,6.776088e+07,Big Beach Films,109.0
0,A Quiet Place,PG-13,Drama,2018,"April 6, 2018 (United States)",7.5,456000.0,John Krasinski,Bryan Woods,Emily Blunt,United States,17000000.0,3.503204e+08,Paramount Pictures,90.0
75,Mid90s,R,Comedy,2018,"October 26, 2018 (United States)",7.4,54000.0,Jonah Hill,Jonah Hill,Sunny Suljic,United States,10000000.0,9.303022e+06,A24,85.0
134,The Death & Life of John F. Donovan,R,Drama,2018,"December 13, 2019 (United States)",6.2,5900.0,Xavier Dolan,Xavier Dolan,Kit Harington,Canada,35000000.0,3.326364e+06,Lyla Films,123.0
99,London Fields,R,Crime,2018,"October 26, 2018 (United States)",4.0,7800.0,Mathew Cullen,Roberta Hanley,Amber Heard,United Kingdom,8000000.0,4.874200e+05,Muse Productions,118.0
152,John Wick: Chapter 3 - Parabellum,R,Action,2019,"May 17, 2019 (United States)",7.4,296000.0,Chad Stahelski,Derek Kolstad,Keanu Reeves,United States,75000000.0,3.272818e+08,Lionsgate,130.0
76,Replicas,PG-13,Drama,2018,"January 11, 2019 (United States)",5.5,34000.0,Jeffrey Nachmanoff,Chad St. John,Keanu Reeves,United Kingdom,30000000.0,9.330075e+06,Company Films,107.0
232,Abominable,PG,Animation,2019,"September 27, 2019 (United States)",7.0,32000.0,Jill Culton,Jill Culton,Chloe Bennet,United States,75000000.0,1.803142e+08,DreamWorks Animation,97.0
114,On the Basis of Sex,PG-13,Biography,2018,"January 11, 2019 (United States)",7.1,31000.0,Mimi Leder,Daniel Stiepleman,Felicity Jones,United States,20000000.0,3.875590e+07,Alibaba Pictures,120.0
43,The Commuter,PG-13,Action,2018,"January 12, 2018 (United States)",6.3,107000.0,Jaume Collet-Serra,Byron Willinger,Liam Neeson,United States,30000000.0,1.199424e+08,StudioCanal,104.0
257,Clinton Road,NaN,Horror,2019,"June 14, 2019 (United States)",5.9,1900.0,Richard Grieco,Noel Ashman,Ace Young,NaN,2500000.0,5.040000e+04,Growing Tree Productions,77.0
199,Rambo: Last Blood,R,Action,2019,"September 20, 2019 (United States)",6.1,87000.0,Adrian Grunberg,Matthew Cirulnick,Sylvester Stallone,United States,50000000.0,9.149035e+07,Lionsgate,89.0
141,Goosebumps 2: Haunted Halloween,PG,Animation,2018,"October 12, 2018 (United States)",5.6,19000.0,Ari Sandel,Rob Lieber,Wendi McLendon-Covey,United States,35000000.0,9.332038e+07,Sony Pictures Animation,90.0
14,Ant-Man and the Wasp,PG-13,Action,2018,"July 6, 2018 (United States)",7.0,333000.0,Peyton Reed,Chris McKenna,Paul Rudd,United States,162000000.0,6.226741e+08,Marvel Studios,118.0
148,Escape Room,PG-13,Action,2019,"January 4, 2019 (United States)",6.4,97000.0,Adam Robitel,Bragi F. Schut,Taylor Russell,United States,9000000.0,1.557121e+08,Columbia Pictures,99.0
168,Ready or Not,R,Action,2019,"August 21, 2019 (United States)",6.9,121000.0,Matt Bettinelli-Olpin,Guy Busick,Samara Weaving,United States,6000000.0,5.761578e+07,Fox Searchlight Pictures,95.0
131,The 15:17 to Paris,PG-13,Biography,2018,"February 9, 2018 (United States)",5.3,30000.0,Clint Eastwood,Dorothy Blyskal,Alek Skarlatos,United States,30000000.0,5.707629e+07,Warner Bros.,94.0
133,Super Troopers 2,R,Comedy,2018,"April 20, 2018 (United States)",6.1,25000.0,Jay Chandrasekhar,Jay Chandrasekhar,Jay Chandrasekhar,United States,13500000.0,3.162639e+07,Votiv Films,99.0
224,Shaft,R,Action,2019,"June 14, 2019 (United States)",6.4,48000.0,Tim Story,Ernest Tidyman,Samuel L. Jackson,United States,35000000.0,2.136022e+07,Davis Entertainment,111.0
109,Unsane,R,Drama,2018,"March 23, 2018 (United States)",6.4,42000.0,Steven Soderbergh,Jonathan Bernstein,Claire Foy,United States,1500000.0,1.429360e+07,Fingerprint Releasing,98.0
246,Missing Link,PG,Animation,2019,"April 12, 2019 (United States)",6.7,23000.0,Chris Butler,Chris Butler,Hugh Jackman,Canada,100000000.0,2.656571e+07,Annapurna Pictures,93.0
271,More to Life,NaN,Drama,2020,"October 23, 2020 (United States)",3.1,18.0,Joseph Ebanks,Joseph Ebanks,Shannon Bond,United States,7000.0,NaN,NaN,90.0
162,Star Wars: Episode IX - The Rise of Skywalker,PG-13,Action,2019,"December 20, 2019 (United States)",6.5,394000.0,J.J. Abrams,Chris Terrio,Daisy Ridley,United States,275000000.0,1.078233e+09,Walt Disney Pictures,141.0
135,Stan & Ollie,PG,Biography,2018,"January 11, 2019 (United Kingdom)",7.2,34000.0,Jon S. Baird,Jeff Pope,Steve Coogan,United Kingdom,10000000.0,2.442092e+07,Entertainment One,98.0
72,First Man,PG-13,Biography,2018,"October 12, 2018 (United States)",7.3,176000.0,Damien Chazelle,Josh Singer,Ryan Gosling,United States,59000000.0,1.057132e+08,Universal Pictures,141.0
144,Once Upon a Time... In Hollywood,R,Comedy,2019,"July 26, 2019 (United States)",7.6,603000.0,Quentin Tarantino,Quentin Tarantino,Leonardo DiCaprio,United States,90000000.0,3.745658e+08,Columbia Pictures,161.0
16,The Predator,R,Action,2018,"September 14, 2018 (United States)",5.3,120000.0,Shane Black,Fred Dekker,Boyd Holbrook,United States,88000000.0,1.605421e+08,Twentieth Century Fox,107.0
252,A Madea Family Funeral,PG-13,Comedy,2019,"March 1, 2019 (United States)",4.5,4000.0,Tyler Perry,Tyler Perry,Tyler Perry,United States,20000000.0,7.474772e+07,The Tyler Perry Company,109.0
41,The Nun,R,Horror,2018,"September 7, 2018 (United States)",5.3,127000.0,Corin Hardy,Gary Dauberman,Demián Bichir,United States,22000000.0,3.655517e+08,Atomic Monster,96.0
157,Spider-Man: Far from Home,PG-13,Action,2019,"July 2, 2019 (United States)",7.5,359000.0,Jon Watts,Chris McKenna,Tom Holland,United States,160000000.0,1.131928e+09,Columbia Pictures,129.0
68,Tomb Raider,PG-13,Action,2018,"March 16, 2018 (United States)",6.3,197000.0,Roar Uthaug,Geneva Robertson-Dworet,Alicia Vikander,United Kingdom,94000000.0,2.746508e+08,Warner Bros.,119.0
251,Overcomer,PG,Drama,2019,"August 23, 2019 (United States)",6.6,4100.0,Alex Kendrick,Alex Kendrick,Alex Kendrick,United States,5000000.0,3.802610e+07,Affirm Films,119.0
186,Angel Has Fallen,R,Action,2019,"August 23, 2019 (United States)",6.4,86000.0,Ric Roman Waugh,Robert Mark Kamen,Gerard Butler,United States,40000000.0,1.466620e+08,Millennium Media,121.0
123,Smallfoot,PG,Animation,2018,"September 28, 2018 (United States)",6.6,36000.0,Karey Kirkpatrick,Karey Kirkpatrick,Channing Tatum,United States,80000000.0,2.140401e+08,Warner Animation Group,96.0
6,A Simple Favor,R,Comedy,2018,"September 14, 2018 (United States)",6.8,136000.0,Paul Feig,Darcey Bell,Anna Kendrick,Canada,20000000.0,9.764462e+07,BRON Studios,117.0
205,Pokémon Detective Pikachu,PG,Action,2019,"May 10, 2019 (United States)",6.6,146000.0,Rob Letterman,Dan Hernandez,Ryan Reynolds,United States,150000000.0,4.339213e+08,Warner Bros.,104.0
163,Ford v Ferrari,PG-13,Action,2019,"November 15, 2019 (United States)",8.1,323000.0,James Mangold,Jez Butterworth,Matt Damon,United States,97600000.0,2.255082e+08,Chernin Entertainment,152.0
268,Black Wall Street Burning,R,Drama,2020,"February 7, 2020 (United States)",6.6,35.0,Marcus Brown,Dekoven Riggins,Dan Belcher,United States,5000.0,NaN,Notis Studio,78.0
192,The Peanut Butter Falcon,PG-13,Adventure,2019,"August 23, 2019 (United States)",7.6,73000.0,Tyler Nilson,Tyler Nilson,Zack Gottsagen,United States,6200000.0,1.330315e+08,Armory Films,97.0
150,Yesterday,PG-13,Comedy,2019,"June 28, 2019 (United States)",6.8,131000.0,Danny Boyle,Richard Curtis,Himesh Patel,United Kingdom,26000000.0,1.531934e+08,Decibel Films,116.0
173,Booksmart,R,Comedy,2019,"May 24, 2019 (United States)",7.2,102000.0,Olivia Wilde,Emily Halpern,Kaitlyn Dever,United States,6000000.0,2.495961e+07,Annapurna Pictures,102.0
119,The Nutcracker and the Four Realms,PG,Adventure,2018,"November 2, 2018 (United States)",5.6,30000.0,Lasse Hallström,Ashleigh Powell,Mackenzie Foy,United States,120000000.0,1.739611e+08,Walt Disney Pictures,99.0
178,Aladdin,PG,Adventure,2019,"May 24, 2019 (United States)",6.9,239000.0,Guy Ritchie,John August,Will Smith,United Kingdom,183000000.0,1.050694e+09,Walt Disney Pictures,128.0
185,Long Shot,R,Comedy,2019,"May 3, 2019 (United States)",6.8,101000.0,Jonathan Levine,Dan Sterling,Charlize Theron,United States,40000000.0,5.387381e+07,Summit Entertainment,125.0

In [33]:
stratified_sample.head(30)

,name,rating,genre,year,released,score,votes,director,writer,star,country,budget,gross,company,runtime
22,Annihilation,R,Adventure,2018,"February 23, 2018 (United States)",6.8,292000.0,Alex Garland,Alex Garland,Natalie Portman,United Kingdom,40000000.0,4.307092e+07,Paramount Pictures,115.0
78,Searching,PG-13,Drama,2018,"August 31, 2018 (United States)",7.6,148000.0,Aneesh Chaganty,Aneesh Chaganty,John Cho,United States,880000.0,7.546204e+07,Screen Gems,102.0
155,Captain Marvel,PG-13,Action,2019,"March 8, 2019 (United States)",6.8,478000.0,Anna Boden,Anna Boden,Brie Larson,United States,160000000.0,1.128463e+09,Walt Disney Pictures,123.0
226,The Kitchen,R,Action,2019,"August 9, 2019 (United States)",5.5,18000.0,Andrea Berloff,Andrea Berloff,Melissa McCarthy,United States,38000000.0,1.598003e+07,BRON Studios,102.0
124,Hell Fest,R,Horror,2018,"September 28, 2018 (United States)",5.5,15000.0,Gregory Plotkin,Seth M. Sherwood,Cynthea Mercado,United States,5500000.0,1.816093e+07,CBS Films,89.0
26,Death Wish,R,Action,2018,"March 2, 2018 (United States)",6.3,67000.0,Eli Roth,Joe Carnahan,Bruce Willis,United States,30000000.0,4.956271e+07,Cave 76,107.0
87,Hotel Artemis,R,Action,2018,"June 8, 2018 (United States)",6.1,49000.0,Drew Pearce,Drew Pearce,Jodie Foster,United Kingdom,15000000.0,1.331358e+07,The Ink Factory,94.0
183,Toy Story 4,G,Animation,2019,"June 21, 2019 (United States)",7.7,217000.0,Josh Cooley,John Lasseter,Tom Hanks,United States,200000000.0,1.073395e+09,Pixar Animation Studios,100.0
89,Book Club,PG-13,Comedy,2018,"May 18, 2018 (United States)",6.1,26000.0,Bill Holderman,Bill Holderman,Diane Keaton,United States,10000000.0,1.044382e+08,Apartment Story,104.0
247,Breakthrough,PG,Biography,2019,"April 17, 2019 (United States)",6.3,8800.0,Roxann Dawson,Joyce Smith,Marcel Ruiz,United States,14000000.0,5.044436e+07,Fox 2000 Pictures,116.0
100,Andhadhun,Not Rated,Crime,2018,"October 5, 2018 (United States)",8.2,79000.0,Sriram Raghavan,Arijit Biswas,Ayushmann Khurrana,India,4500000.0,6.247534e+07,Matchbox Pictures,139.0
203,A Beautiful Day in the Neighborhood,PG,Biography,2019,"November 22, 2019 (United States)",7.3,67000.0,Marielle Heller,Micah Fitzerman-Blue,Tom Hanks,China,25000000.0,6.776088e+07,Big Beach Films,109.0
0,A Quiet Place,PG-13,Drama,2018,"April 6, 2018 (United States)",7.5,456000.0,John Krasinski,Bryan Woods,Emily Blunt,United States,17000000.0,3.503204e+08,Paramount Pictures,90.0
75,Mid90s,R,Comedy,2018,"October 26, 2018 (United States)",7.4,54000.0,Jonah Hill,Jonah Hill,Sunny Suljic,United States,10000000.0,9.303022e+06,A24,85.0
134,The Death & Life of John F. Donovan,R,Drama,2018,"December 13, 2019 (United States)",6.2,5900.0,Xavier Dolan,Xavier Dolan,Kit Harington,Canada,35000000.0,3.326364e+06,Lyla Films,123.0
99,London Fields,R,Crime,2018,"October 26, 2018 (United States)",4.0,7800.0,Mathew Cullen,Roberta Hanley,Amber Heard,United Kingdom,8000000.0,4.874200e+05,Muse Productions,118.0
152,John Wick: Chapter 3 - Parabellum,R,Action,2019,"May 17, 2019 (United States)",7.4,296000.0,Chad Stahelski,Derek Kolstad,Keanu Reeves,United States,75000000.0,3.272818e+08,Lionsgate,130.0
76,Replicas,PG-13,Drama,2018,"January 11, 2019 (United States)",5.5,34000.0,Jeffrey Nachmanoff,Chad St. John,Keanu Reeves,United Kingdom,30000000.0,9.330075e+06,Company Films,107.0
232,Abominable,PG,Animation,2019,"September 27, 2019 (United States)",7.0,32000.0,Jill Culton,Jill Culton,Chloe Bennet,United States,75000000.0,1.803142e+08,DreamWorks Animation,97.0
114,On the Basis of Sex,PG-13,Biography,2018,"January 11, 2019 (United States)",7.1,31000.0,Mimi Leder,Daniel Stiepleman,Felicity Jones,United States,20000000.0,3.875590e+07,Alibaba Pictures,120.0
43,The Commuter,PG-13,Action,2018,"January 12, 2018 (United States)",6.3,107000.0,Jaume Collet-Serra,Byron Willinger,Liam Neeson,United States,30000000.0,1.199424e+08,StudioCanal,104.0
257,Clinton Road,NaN,Horror,2019,"June 14, 2019 (United States)",5.9,1900.0,Richard Grieco,Noel Ashman,Ace Young,NaN,2500000.0,5.040000e+04,Growing Tree Productions,77.0
199,Rambo: Last Blood,R,Action,2019,"September 20, 2019 (United States)",6.1,87000.0,Adrian Grunberg,Matthew Cirulnick,Sylvester Stallone,United States,50000000.0,9.149035e+07,Lionsgate,89.0
141,Goosebumps 2: Haunted Halloween,PG,Animation,2018,"October 12, 2018 (United States)",5.6,19000.0,Ari Sandel,Rob Lieber,Wendi McLendon-Covey,United States,35000000.0,9.332038e+07,Sony Pictures Animation,90.0
14,Ant-Man and the Wasp,PG-13,Action,2018,"July 6, 2018 (United States)",7.0,333000.0,Peyton Reed,Chris McKenna,Paul Rudd,United States,162000000.0,6.226741e+08,Marvel Studios,118.0
148,Escape Room,PG-13,Action,2019,"January 4, 2019 (United States)",6.4,97000.0,Adam Robitel,Bragi F. Schut,Taylor Russell,United States,9000000.0,1.557121e+08,Columbia Pictures,99.0
168,Ready or Not,R,Action,2019,"August 21, 2019 (United States)",6.9,121000.0,Matt Bettinelli-Olpin,Guy Busick,Samara Weaving,United States,6000000.0,5.761578e+07,Fox Searchlight Pictures,95.0
131,The 15:17 to Paris,PG-13,Biography,2018,"February 9, 2018 (United States)",5.3,30000.0,Clint Eastwood,Dorothy Blyskal,Alek Skarlatos,United States,30000000.0,5.707629e+07,Warner Bros.,94.0
133,Super Troopers 2,R,Comedy,2018,"April 20, 2018 (United States)",6.1,25000.0,Jay Chandrasekhar,Jay Chandrasekhar,Jay Chandrasekhar,United States,13500000.0,3.162639e+07,Votiv Films,99.0
224,Shaft,R,Action,2019,"June 14, 2019 (United States)",6.4,48000.0,Tim Story,Ernest Tidyman,Samuel L. Jackson,United States,35000000.0,2.136022e+07,Davis Entertainment,111.0

In [34]:
stratified_sample.describe()

,year,score,votes,budget,gross,runtime
count,55.000000,55.000000,55.000000,5.500000e+01,5.300000e+01,55.000000
mean,2018.545455,6.483636,122482.781818,5.234895e+07,2.122498e+08,108.763636
std,0.571489,0.963551,138902.961081,6.064599e+07,3.137791e+08,17.746114
min,2018.000000,3.100000,18.000000,5.000000e+03,5.040000e+04,77.000000
25%,2018.000000,6.100000,28000.000000,1.000000e+07,3.162639e+07,96.500000
50%,2019.000000,6.600000,73000.000000,3.000000e+07,9.149035e+07,104.000000
75%,2019.000000,7.150000,147000.000000,7.750000e+07,2.140401e+08,119.000000
max,2020.000000,8.200000,603000.000000,2.750000e+08,1.131928e+09,161.000000

In [35]:
import scipy.stats as stats
import math

#specify sample mean (x_bar), sample standard deviation (s),
#sample size (n) and confidance level
x_bar = 5.23 #rata-rata
s = 6.06 #std sample
n = 5.50 #jumlah data (sample)
confidence_level = 0.90 #pilih antara 0.90 / 0.95 / 0.99

#calculate alpha, degrees of freedem (df), the critical t-value,
#and the margin of error
alpha = (1-confidence_level)
df = n - 1
standard_error = s/math.sqrt(n)
critical_t = stats.t.ppf(1-alpha/2, df)
margin_of_error = critical_t * standard_error

#calculate the lower and upper bound of the confidence interval
lower_bound = x_bar - margin_of_error
upper_bound = x_bar + margin_of_error

#print the results
print("Critical t-value: {:.2f}".format(critical_t))
print("Margin of error: {:.2f}".format(margin_of_error))
print("Confidence interval: ({:.2f}, {:.2f})".format(lower_bound, upper_bound))
print("The {:.1%} confidence interval for the population mean is:".format(confidence_level))
print("between {:.2f} and {:.2f}".format(lower_bound, upper_bound))

Critical t-value: 2.07
Margin of error: 5.34
Confidence interval: (-0.11, 10.57)
The 90.0% confidence interval for the population mean is:
between -0.11 and 10.57